development:
  sessions:
    default:
      database: gdzlla_development
      hosts:
        - localhost:27017
      options:
  options:
    allow_dynamic_fields: false
    preload_models: true

test:
  sessions:
    default:
      database: gdzlla_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    allow_dynamic_fields: false
    preload_models: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
  options:
    allow_dynamic_fields: false
    preload_models: true
