defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: gdzlla_development

test:
  <<: *defaults
  database: gdzlla_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
